### PR TITLE
Fix auto indent options when autoindent is on

### PR DESCRIPTION
**Pull request by bew**
I don't know if it's the right file, correct me if it's wrong !

### CODE REVIEW

**Comment by rhysd** [comment]
Please tell me what was a problem before this change.  AFAIK there is no limitation about indentation (indent width and use hard tab or not) for Crystal.

**Comment by bew** [comment]
As stated in the coding style convention : https://crystal-lang.org/docs/conventions/coding_style.html :

> Use two spaces to indent code inside namespaces, methods, blocks or other nested contexts.

And I was tired doing `:CrystalFormat` when I add some code. As vim-crystal has an indent plugin, the code is correctly indented, but not with the right amount of Whitespaces.. This pull request should fix the number of Whitespace used for indentation.. 

As you said : 

> Crystal has no limitation about indentation

Maybe the convention settings could be enable via a global variable (e.g. `g:crystal_convention`) which is by default disabled.. 

What do you think ?

**Comment by bew** [comment]
Anything?

**Comment by rhysd** [comment]
Even Go filetype plugin bundled in Vim, it does not set indentation config in `ftplugin/go.vim`. I agree with respecting official Crystal code style, but we should not force code style to users. Users can simply write indentation config to `.vimrc`.

```vim
autocmd FileType crystal setlocal expandtab shiftwidth=2 softtabstop=2 tabstop=2
```

**Pull request closed without merging**
